services:
  application:
    image: notion_reader:0.0.1
    container_name: notion_reader
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/notion_reader_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:14-bullseye
    container_name: notion_reader-postgres
    environment:
      - POSTGRES_DB=notion_reader_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - notion_reader_psql:/var/lib/postgresql/data
volumes:
  notion_reader_psql:
